-- Storage Group
CREATE STOGROUP SG_HOT1
ON '/db2data1/db2inst', '/db2data2/db2inst'
DATA TAG NONE;

-- Bufferpool
CREATE BUFFERPOOL IBMP4KB PAGESIZE 4096;
CREATE BUFFERPOOL IBMP8KB PAGESIZE 8192;
CREATE BUFFERPOOL IBMP16KB PAGESIZE 16384;

-- Index Tablespace
CREATE LARGE TABLESPACE IDX_HOT1
PAGESIZE 4096
MANAGED BY AUTOMATIC STORAGE
USING STOGROUP SG_HOT1
AUTORESIZE YES
BUFFERPOOL IBMP4KB;

-- Long Tablespace
CREATE LARGE TABLESPACE LOB_HOT1
PAGESIZE 8192
MANAGED BY AUTOMATIC STORAGE
USING STOGROUP SG_HOT1
AUTORESIZE YES
BUFFERPOOL IBMP8KB;

-- Tablespace 16 K for table
CREATE LARGE TABLESPACE REG_HOT1
PAGESIZE 16384
MANAGED BY AUTOMATIC STORAGE
USING STOGROUP SG_HOT1
AUTORESIZE YES
BUFFERPOOL IBMP16KB;

--DROP BUFFERPOOL IBMP4KB;
--DROP BUFFERPOOL IBMP8KB;
--DROP BUFFERPOOL IBMP16KB;
--
--DROP TABLESPACE IDX_HOT1;
--DROP TABLESPACE LOB_HOT1;
--DROP TABLESPACE REG_HOT1;

-- Create Schema
CREATE SCHEMA CAR_RENTAL_SCHEMA;

-- DROP SCHEMA CAR_RENTAL_SCHEMA RESTRICT;