-- Table location
CREATE TABLE CAR_RENTAL_SCHEMA.LOCATION(
	ID_LOCATION SMALLINT NOT NULL PRIMARY KEY,
    STREET_ADDRESS VARCHAR(100) NOT NULL,
	CITY VARCHAR (50) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    ZIPCODE INT NOT NULL
)
IN REG_HOT1
INDEX IN IDX_HOT1
LONG IN LOB_HOT1;

-- Zip Code index Unique
CREATE UNIQUE INDEX ZIPCODE_UNIQUE_INDEX ON CAR_RENTAL_SCHEMA.LOCATION (ZIPCODE);

-- Table Customer
CREATE TABLE CAR_RENTAL_SCHEMA.CUSTOMER(
	ID_CUSTOMER SMALLINT NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(45) NOT NULL,
	LAST_NAME VARCHAR (45) NOT NULL,
    DOB DATE NOT NULL,
    DRIVER_LICENSE_NUMBER VARCHAR(13) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(12) NULL

    -- Unique Index
--    UNIQUE INDEX `driver_license_number_UNIQUE` (`driver_license_number` ASC),
--    UNIQUE INDEX `email_UNIQUE` (`email` ASC)
)
IN REG_HOT1
INDEX IN IDX_HOT1
LONG IN LOB_HOT1;

