-- Table location
CREATE TABLE CAR_RENTAL_SCHEMA.LOCATION(
	ID_LOCATION SMALLINT NOT NULL PRIMARY KEY,
    STREET_ADDRESS VARCHAR(100) NOT NULL,
	CITY VARCHAR (50) NOT NULL,
    STATE VARCHAR(2) NOT NULL,
    ZIPCODE INT NOT NULL
)
IN REG_HOT1
INDEX IN IDX_HOT1
LONG IN LOB_HOT1;

-- Zip Code index Unique
CREATE UNIQUE INDEX ZIPCODE_UNIQUE_INDEX ON CAR_RENTAL_SCHEMA.LOCATION (ZIPCODE);

-- Table Customer
CREATE TABLE CAR_RENTAL_SCHEMA.CUSTOMER(
	ID_CUSTOMER SMALLINT NOT NULL PRIMARY KEY,
    FIRST_NAME VARCHAR(45) NOT NULL,
	LAST_NAME VARCHAR (45) NOT NULL,
    DOB DATE NOT NULL,
    DRIVER_LICENSE_NUMBER VARCHAR(13) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PHONE VARCHAR(12) NULL
)
IN REG_HOT1
INDEX IN IDX_HOT1
LONG IN LOB_HOT1;

-- Table Vehicle
CREATE TABLE CAR_RENTAL_SCHEMA.VEHICLE (
    ID_VEHICLE INT NOT NULL PRIMARY KEY,
    brand VARCHAR(45) NOT NULL,
    model VARCHAR(45) NOT NULL,
    model_year INT NOT NULL,
    mileage INT  NOT NULL,
    color VARCHAR(45) NOT NULL,
    vehicle_type_id INT NOT NULL,
    current_location_id INT NOT NULL
)
IN REG_HOT1
INDEX IN IDX_HOT1
LONG IN LOB_HOT1;