CREATE OR REPLACE TRIGGER age_check BEFORE INSERT ON CAR_RENTAL_SCHEMA.CUSTOMER FOR EACH ROW
BEGIN
DECLARE age INT;
SELECT (YEAR(CURRENT DATE) - YEAR(DOB)) INTO age FROM CAR_RENTAL_SCHEMA.CUSTOMER;
    IF (age < 21) THEN
    SIGNAL SQLSTATE '45000'
            SET MESSAGE_TEXT = 'customer age_check constraint on customer.dob failed';
    END IF;
END@